"""Figure 2.  The digitized period means reproduce the averages the original printed,
with residuals at the rounding floor of that printed table.

Regenerated by figures.py; do not run directly.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from figstyle import META_GREY, apply_figure_style, panel_letter  # noqa: E402

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt



HT = pd.read_csv(ROOT / "out" / "human_trades.csv")
DQ = pd.read_csv(ROOT / "tab" / "D0_digitization_quality.csv")

val = DQ[~DQ["dot_quality_flag"].str.contains("source_inconsistent|mean_mismatch", na=False)]

apply_figure_style(sizes=(9, 8, 7))
fig2p, (a1, a2) = plt.subplots(1, 2, figsize=(6.9, 2.8))
v = val.copy()
a1.scatter(v["mean_printed"], v["mean_digitized"], s=18, color="#3b6ea5", alpha=.75, lw=0)
lim = [140, 420]
a1.plot(lim, lim, color=META_GREY, lw=0.9, ls="--")
a1.set_xlim(*lim)
a1.set_ylim(*lim)
a1.set_xlabel("Average price printed by P&S (francs)")
a1.set_ylabel("Average of digitized trades")
a1.set_title("Digitized period means reproduce\nthe published averages")
a1.text(150, 395, f"$n={len(v)}$ periods\nmedian $|$residual$|$ = {v['mean_residual'].abs().median():.2f} f\nmax = {v['mean_residual'].abs().max():.2f} f",
        fontsize=6.5, linespacing=1.4, va="top")
resid = v["mean_residual"]
a2.hist(resid, bins=np.arange(-3, 3.01, 0.4), color="#3b6ea5", alpha=.85)
a2.axvline(0, color=META_GREY, lw=0.9, ls="--")
a2.set_xlabel("Digitized minus printed mean (francs)")
a2.set_ylabel("Periods")
a2.set_title("Residuals sit at the rounding floor\nof the published table")
a2.axvspan(-0.5, 0.5, color=META_GREY, alpha=0.13, zorder=0)
a2.text(0.62, 13.6, "P&S round to\nwhole francs", fontsize=6.5, color=META_GREY, linespacing=1.3)
for L, ax_ in zip("ab", [a1, a2]):
    panel_letter(ax_, L)
fig2p.tight_layout(w_pad=1.7)
fig2p.savefig(ROOT / "fig" / "fig2_digitization.png", dpi=300)
