"""Figure 3.  Buyer-side prices climb inside the period while seller-side periods open at
the fully revealing price; the buyer-side gap closes within the period and closes short;
and repetition lifts the opening price, not the closing price.

Regenerated by figures.py; do not run directly.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from figstyle import META_GREY, apply_figure_style, panel_letter  # noqa: E402

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt



HTS = pd.read_csv(ROOT / "tab" / "trade_level_scored.csv")
C = pd.read_csv(ROOT / "tab" / "trajectory.csv")
A = pd.read_csv(ROOT / "tab" / "period_table.csv")

ins = A[(A["market"].isin([3, 4, 5])) & (A["info"] == "insider") & (A["side"].isin(["buyer", "seller"]))].copy()

apply_figure_style(sizes=(8, 7, 6))

BUY, SELL = "#1f6fb4", "#c2571a"

h = HTS[(HTS["market"].isin([3, 4, 5])) & (HTS["info"] == "insider") & (HTS["side"].isin(["buyer", "seller"]))].copy()
h["u"] = (h["trade_index"] - 1) / (h["n_trades_in_period"] - 1).replace(0, np.nan)
h["Dc"] = (h["price"] - h["vbar"]) / (h["re_price"] - h["vbar"])

dec = C[(C["nbins"] == 10) & (C["sample"] == "human m3-5 insider (primary)")]

pos = {"seller": [0, 1], "buyer": [2.2, 3.2]}

gb = ins[(ins["side"] == "buyer") & ins["k_state"].notna()]

LO, HI = -1.35, 1.95

apply_figure_style(sizes=(8, 7, 6))
fig, axes = plt.subplots(1, 3, figsize=(7.4, 2.6))
ax = axes[0]
for (m, p), g in h.groupby(["market", "period"]):
    g = g.sort_values("trade_index")
    col = BUY if g["side"].iloc[0] == "buyer" else SELL
    ax.plot(g["u"], g["Dc"].clip(LO + 0.02, HI - 0.02), color=col, lw=0.7, alpha=0.4)
for side, col in [("buyer", BUY), ("seller", SELL)]:
    d = dec[dec["side"] == side].sort_values("bin")
    ax.plot((d["bin_lo"] + d["bin_hi"]) / 2, d["D_mean"], color=col, lw=2.3, marker="o", ms=3.5, zorder=5)
ax.axhline(1, color=META_GREY, lw=0.8, ls="--", zorder=1)
ax.set_xlabel("Position within period\n(0 = first trade, 1 = last)")
ax.set_ylabel("Price, normalized ($D$)")
ax.set_title("Buyer-side prices climb inside the\nperiod; seller-side open at RE")
ax.text(0.40, 1.31, "informed selling", color=SELL, fontsize=6)
ax.text(0.40, 0.52, "informed buying", color=BUY, fontsize=6)
ax.annotate("RE price", xy=(1.0, 1.0), xytext=(0.60, 1.72), fontsize=6, color=META_GREY,
            arrowprops=dict(arrowstyle="-", lw=0.6, color=META_GREY, shrinkA=0, shrinkB=1))
ax.set_ylim(LO, HI)
ax.margins(x=0.04)

ax = axes[1]
# One RNG per (side, measure) rather than one shared stream, so the jitter of each
# group depends only on that group -- a change to one group cannot shift another's.
for si, (side, col) in enumerate([("seller", SELL), ("buyer", BUY)]):
    g = ins[ins["side"] == side]
    for mi, (m, x) in enumerate([("D_first", pos[side][0]), ("D_last", pos[side][1])]):
        v = g[m].clip(LO + 0.02, HI - 0.02).values
        jit = np.random.default_rng(100 + 10 * si + mi).normal(0, .05, len(v))
        ax.scatter(np.full(len(v), x) + jit, v, s=9, color=col, alpha=.55, lw=0)
        ax.plot([x - .24, x + .24], [g[m].mean()] * 2, color=col, lw=2.2)
    ax.plot(pos[side], [g["D_first"].mean(), g["D_last"].mean()], color=col, lw=1, ls=":")
ax.axhline(1, color=META_GREY, lw=0.8, ls="--")
ax.set_xticks([0, 1, 2.2, 3.2])
ax.set_xticklabels(["first", "last", "first", "last"])
ax.set_ylabel("$D$ at that trade")
ax.set_title("The buyer-side gap closes within\nthe period, and closes short")
ax.text(0.5, LO + 0.10, "informed selling", color=SELL, fontsize=6, ha="center")
ax.text(2.7, LO + 0.10, "informed buying", color=BUY, fontsize=6, ha="center")
ax.set_ylim(LO, HI)
ax.set_xlim(-0.55, 3.75)

ax = axes[2]
for m, mk, col in [("D_last", "s", "#7fb3d8"), ("D_first", "o", BUY)]:
    agg = gb.groupby("k_state")[m].mean()
    ax.scatter(gb["k_state"], gb[m].clip(LO + 0.02, HI - 0.02), s=8, alpha=.4, lw=0, color=col)
    ax.plot(agg.index, agg.values, marker=mk, ms=4.2, lw=1.8, color=col)
ax.axhline(1, color=META_GREY, lw=0.8, ls="--")
ax.set_xlabel("$k$-th occurrence of the same state")
ax.set_ylabel("$D$")
ax.set_title("Repetition lifts the opening price,\nnot the closing price")
ax.text(2.18, 1.16, "last trade", color="#5a92bd", fontsize=6)
ax.text(2.18, 0.32, "first trade", color=BUY, fontsize=6)
ax.set_xticks([1, 2, 3, 4])
ax.set_ylim(LO, HI)
ax.margins(x=0.08)

for L, ax in zip("abc", axes):
    panel_letter(ax, L)
fig.tight_layout(w_pad=1.5)

# Fix panel a: remove annotate RE price text, add simple RE label on axis
ax = axes[0]
for t in list(ax.texts):
    if "RE price" in t.get_text() or "informed selling" in t.get_text():
        t.remove()
ax.text(0.40, 1.31, "informed selling", color=SELL, fontsize=6)
ax.text(1.005, 1.0, "RE", color=META_GREY, fontsize=6, va="center", ha="left",
        transform=ax.get_yaxis_transform())

# Fix panel b: move informed buying label to top
ax = axes[1]
for t in list(ax.texts):
    if "informed buying" in t.get_text():
        t.remove()
ax.text(2.7, HI - 0.13, "informed buying", color=BUY, fontsize=6, ha="center", va="top")

fig.savefig(ROOT / "fig" / "fig3_within_period.png", dpi=300)
