"""Figure 4.  The information-free account: the two sides open on opposite sides of the
uninformed level, and the buying side's climb is nine times the drift measured without
information.

Regenerated by figures.py; do not run directly.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from figstyle import META_GREY, apply_figure_style, panel_letter  # noqa: E402

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib as mpl
import matplotlib.pyplot as plt



pp = pd.read_csv(ROOT / "tab" / "period_paths_francs.csv")

ins35 = pp[(pp['info'] == 'insider') & (pp['market'].isin([3, 4, 5]))]

NI = pp[pp['info'] == 'none'].copy()
NI['flagged'] = NI['flag'].astype(str).str.contains('mean_mismatch|source_inconsistent')
BENCH = NI[NI['period'] != 1]
SELLp = ins35[ins35.side == 'seller']
BUYp = ins35[ins35.side == 'buyer']
drift = BENCH['francs_change'].mean()
disc = BENCH['first_minus_vbar'].mean()

alt_drifts = [NI[NI['period'] != 1]['francs_change'].mean(),
              NI[(NI['period'] != 1) & (~NI['flagged'])]['francs_change'].mean(),
              NI[(NI['period'] != 1) & (NI['flag'] == 'ok')]['francs_change'].mean(),
              NI[(NI['market'].isin([3, 4, 5])) & (NI['period'] != 1)]['francs_change'].mean()]
alt_discs = [NI[NI['period'] != 1]['first_minus_vbar'].mean(),
             NI[(NI['period'] != 1) & (~NI['flagged'])]['first_minus_vbar'].mean(),
             NI[(NI['period'] != 1) & (NI['flag'] == 'ok')]['first_minus_vbar'].mean(),
             NI[(NI['market'].isin([3, 4, 5])) & (NI['period'] != 1)]['first_minus_vbar'].mean(),
             NI['first_minus_vbar'].mean()]

apply_figure_style(sizes=(9, 8, 7))
BUYC, SELLC, NIC = "#1f6fb4", "#c2571a", "#7a7a7a"

groups = [("no information", BENCH['first_minus_vbar'].values, NIC),
          ("informed\nselling", SELLp['first_minus_vbar'].values, SELLC),
          ("informed\nbuying", BUYp['first_minus_vbar'].values, BUYC)]

groups2 = [("no information", BENCH['francs_change'].values, NIC),
           ("informed\nselling", SELLp['francs_change'].values, SELLC),
           ("informed\nbuying", BUYp['francs_change'].values, BUYC)]

fig4, (axa, axb) = plt.subplots(1, 2, figsize=(6.9, 2.95))

ax = axa
ax.axhspan(min(alt_discs), max(alt_discs), color=NIC, alpha=.15, lw=0, zorder=1)
for i, (lab, v, c) in enumerate(groups):
    j = np.random.default_rng(7 + i).normal(0, 0.075, len(v))
    ax.scatter(np.full(len(v), i) + j, v, s=20, color=c, alpha=.7, lw=0, zorder=3)
    ax.plot([i - 0.28, i + 0.28], [v.mean()] * 2, color=c, lw=2.6, zorder=4, solid_capstyle="butt")
ax.axhline(0, color="#444", lw=0.9, ls="--", zorder=2)
ax.axhline(disc, color=NIC, lw=1.4, ls=":", zorder=2)
ax.set_xticks(range(3))
ax.set_xticklabels([g[0] for g in groups])
ax.set_ylabel("First trade of period,\nfrancs relative to $\\bar v$")
ax.set_title("The two sides open on opposite\nsides of the uninformed level")
ax.text(-0.52, 8, "$\\bar v$", fontsize=7.5, color="#444")
ax.text(-0.52, min(alt_discs) - 8, "state-independent prediction\n(shaded: benchmark range)",
        fontsize=6, color=NIC, ha="left", va="top", linespacing=1.35)
ax.annotate("", xy=(1.5, -39.5), xytext=(1.5, 36.2),
            arrowprops=dict(arrowstyle="<->", lw=0.8, color="#333", shrinkA=0, shrinkB=0))
ax.text(1.57, -2, "75.7 f", fontsize=6.5, color="#333", ha="left", va="center")
ax.set_ylim(-150, 150)
ax.set_xlim(-0.66, 2.42)

ax = axb
ax.axhspan(min(alt_drifts), max(alt_drifts), color=NIC, alpha=.15, lw=0, zorder=1)
for i, (lab, v, c) in enumerate(groups2):
    j = np.random.default_rng(21 + i).normal(0, 0.075, len(v))
    ax.scatter(np.full(len(v), i) + j, v, s=20, color=c, alpha=.7, lw=0, zorder=3)
    ax.plot([i - 0.28, i + 0.28], [v.mean()] * 2, color=c, lw=2.6, zorder=4, solid_capstyle="butt")
ax.axhline(0, color="#444", lw=0.9, ls="--", zorder=2)
ax.axhline(drift, color=NIC, lw=1.4, ls=":", zorder=2)
ax.set_xticks(range(3))
ax.set_xticklabels([g[0] for g in groups2])
ax.set_ylabel("Francs moved within period\n(last trade minus first)")
ax.set_title("The buying side's climb is nine times\nthe drift measured without information")
ax.text(-0.52, -55, "drift without information,\n$+7.7$ f (shaded: range)", fontsize=6, color=NIC,
        va="center", ha="left", linespacing=1.35)
ax.annotate("", xy=(-0.20, drift), xytext=(-0.06, -46),
            arrowprops=dict(arrowstyle="-", lw=0.5, color=NIC))
ax.text(2.02, 112, "$+70.9$ f", fontsize=6.5, color=BUYC, ha="center")
ax.set_ylim(-108, 140)
ax.set_xlim(-0.66, 2.42)

for L, a_ in zip("ab", [axa, axb]):
    panel_letter(a_, L)
fig4.tight_layout(w_pad=2.0)

for t in axa.texts:
    if '75.7' in t.get_text():
        t.set_position((1.57, -16))

fig4.savefig(ROOT / "fig" / "fig4_baseline.png", dpi=300)
